services:
  client:
    build:
      context: ./client
      dockerfile: test.Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./client/src:/app/src
      - ./client/__tests__:/app/__tests__
      - ./client/vitest.setup.tsx:/app/vitest.setup.tsx
      - ./client/vite.config.ts:/app/vite.config.ts
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./api
      dockerfile: test.Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./api/src:/app/src
      - ./api/__tests__:/app/__tests__
      - ./api/vitest.setup.ts:/app/vitest.setup.ts
      - ./api/vitest.config.ts:/app/vitest.config.ts
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
  postgres:
    env_file:
      - api/dev.env
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
